### PR TITLE
fix -l option

### PR DESCRIPTION
**Pull request by amacou**
fix can't load -l option files

### CODE REVIEW

**Comment by r7kamura** [comment]
@amacou Thx! Can this patch run on both slop version 3 & 4?

**Comment by amacou** [comment]
sorry, this patch run on version4 only.

**Comment by r7kamura** [comment]
Okay, I'll add runtime dependency on slop version 4.0.0 or higher into gemspec. Thank you for your pull request!

**Comment by amacou** [comment]
Thx!

**Pull request merged**
