### PR TITLE
Use default logger

### PR DESCRIPTION
**Pull request by eagletmt**
Logs should have additional information like timestamp, severity and so
on. Ruby's default logger does it.

### CODE REVIEW

**Comment by eagletmt** [comment]
Moreover, Ruboty::Logger doesn't format exceptions nicely. The default logger formatter logs exception's name and backtrace.

```
irb(main):001:0> require 'ruboty/logger'
=> true
irb(main):002:0> begin raise ArgumentError.new('foo bar'); rescue => err; Ruboty::Logger.new($stdout).error(err); end
foo bar
=> true
irb(main):003:0> begin raise ArgumentError.new('foo bar'); rescue => err; Logger.new($stdout).error(err); end
E, [2016-04-25T23:20:42.420418 #7844] ERROR -- : foo bar (ArgumentError)
(irb):3:in `irb_binding'
/usr/lib/ruby/2.4.0/irb/workspace.rb:87:in `eval'
/usr/lib/ruby/2.4.0/irb/workspace.rb:87:in `evaluate'
/usr/lib/ruby/2.4.0/irb/context.rb:380:in `evaluate'
/usr/lib/ruby/2.4.0/irb.rb:489:in `block (2 levels) in eval_input'
/usr/lib/ruby/2.4.0/irb.rb:623:in `signal_status'
/usr/lib/ruby/2.4.0/irb.rb:486:in `block in eval_input'
/usr/lib/ruby/2.4.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/usr/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `loop'
/usr/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/usr/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `catch'
/usr/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/usr/lib/ruby/2.4.0/irb.rb:485:in `eval_input'
/usr/lib/ruby/2.4.0/irb.rb:395:in `block in start'
/usr/lib/ruby/2.4.0/irb.rb:394:in `catch'
/usr/lib/ruby/2.4.0/irb.rb:394:in `start'
/usr/bin/irb:11:in `<main>'
=> true
```

**Comment by r7kamura** [comment]
Hi @eagletmt, thanks for your Pull Request!

I agree with most of what you say, but somehow the `Ruboty::Adapters::Shell#explain` is using Ruboty.log to show "Type `exit` or `quit` to end the session.". So we should change this code before merging your changes 😩

**Comment by r7kamura** [comment]
Released https://github.com/r7kamura/ruboty/releases/tag/v1.2.3 💎

**Comment by eagletmt** [comment]
thxx

**Pull request merged**
